updated with option for trpc v10
omar-dulaimi/prisma-trpc-generator pull request #53
Opened 2022-12-09 19:25 UTC by mwarger

fixes #52

### Description

Adds support for tRPC v10 via an opt-in option.

2022-12-10 08:42 UTC, omar-dulaimi commented
Hey @mwarger thanks for the PR!
I thought tRPC v10 is stable right now. So, if that was the case, is there any reason to keep this PR behind a flag?

2022-12-10 14:14 UTC, mwarger commented
> Hey @mwarger thanks for the PR!
> I thought tRPC v10 is stable right now. So, if that was the case, is there any reason to keep this PR behind a flag?

Just considering people that may be using this but not upgraded yet. 

I also did this because the middleware and shield features aren't implemented. Wasn't sure how to do that yet.


Happy to remove it, or we can later.

2022-12-16 11:30 UTC, JC-Perso commented
Thx for your work ! 🚀

2022-12-18 14:21 UTC, innellea commented
Any news about this PR @mwarger , @omar-dulaimi  ?

2022-12-19 21:03 UTC, sparkinson-vhs commented
> Any news about this PR @mwarger , @omar-dulaimi ?

I second that. We're currently just starting new project with trpc v10 and would like to use this generator as well.

2022-12-19 21:28 UTC, mwarger commented
@omar-dulaimi @JC-Perso @innellea @sparkinson-vhs This could be published behind a different tag if this is useful - would be nice to have other people test and provide feedback. I'm not familiar with trpc shield so I did not implement that.  I also skipped the middleware because I didn't need it.  I was just trying to get the basics out to start with which is why I put it behind a config option.  I can try to make this more feature complete this week.

2022-12-21 18:40 UTC, omar-dulaimi commented
Hey everybody, I have been a little bit busy lately. But I promise I'll upgrade the shield and shield generator to v10, so we could merge this PR.

@mwarger I think this project will support v10 only going forward, so there's no need for the flag.

2022-12-21 18:42 UTC, mwarger commented
I will take out the flag.

2022-12-21 22:25 UTC, sparkinson-vhs commented
Great! Many thanks to you both.

On Thu, 22 Dec 2022 at 04:42, Mat Warger ***@***.***> wrote:

> I will take out the flag.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/omar-dulaimi/prisma-trpc-generator/pull/53#issuecomment-1361866788>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZP5W7OAY53IXJDX5RCTVY3WONFQ5ANCNFSM6AAAAAASZVT43E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-23 07:36 UTC, omar-dulaimi commented
Hey all, `trpc-shield` has been updated to support `tRPC v10` now starting with `trpc-shield v0.2.0`(latest version is `0.2.1`).
The other project `prisma-trpc-shield-generato` requires no changes at all.

Which means @mwarger can proceed with uncommenting the sections related to them after updating the `trpc-shield` dependency to latest version.

I will add a few comments to this PR since @mwarger is going to need them to use the shield.

We can release as soon as work on this PR is done :)

2022-12-23 07:50 UTC, omar-dulaimi requested changes
Please let me know if you need anything else :)

2022-12-23 07:50 UTC, omar-dulaimi commented on prisma/schema.prisma
> +  v10           = true
No need for the flag anymore. So all changes related below should happen in the original functions(without the v10 duplication)

2022-12-23 07:50 UTC, omar-dulaimi commented on src/helpers.ts
> +  }
Here's how the shield will be used:

```ts
export const permissionsMiddleware = t.middleware(permissions)

export const shieldedProcedure = t.procedure.use(permissionsMiddleware)

export const publicProcedure = t.procedure

```

Then inside routers:

```ts
import { shieldedProcedure, t } from './helpers/createRouter'

export const usersRouter = t.router({
  createOneUser: shieldedProcedure.input(UserCreateOneSchema).mutation(async ({ ctx, input }) => {
    const createOneUser = await ctx.prisma.user.create(input)
    return createOneUser
  }),
});
```

If with middleware:

```ts
export const shieldedProcedure = t.procedure.use(globalMiddleware).use(permissionsMiddleware)

```

2022-12-23 07:50 UTC, omar-dulaimi commented on src/helpers.ts
> +  if (config.withMiddleware) {
As for the middleware:

```ts
export const globalMiddleware = t.middleware(async ({ ctx, next }) => {
  console.log('inside middleware!')
  return next()
})
```

2022-12-23 07:50 UTC, omar-dulaimi commented on README.md
>  - [Supported Prisma Versions](#supported-prisma-versions)
We also need another section for supported tRPC versions

2022-12-24 13:45 UTC, omar-dulaimi commented
Hey @mwarger 
I see that you have removed the flag. Could you also resolve my comments above so we could merge this?

2022-12-24 18:59 UTC, mwarger commented
@omar-dulaimi Changes pushed.  I have not used and am not familiar with trpc shield, so I gave it my best shot.  I have not tested it.  Please review and feel free to push any changes if needed.  Middleware should be good too, I think, but I haven't had a chance to test it.  I just wanted to get the basics out the door based on your comments.  

I also updated dependency versions and updated the README.

2022-12-25 06:20 UTC, omar-dulaimi commented
Looks good to me, thank you @mwarger 
Releasing soon

2022-12-25 07:39 UTC, merged

2022-12-25 07:47 UTC, omar-dulaimi commented
Hey all,
Released in https://github.com/omar-dulaimi/prisma-trpc-generator/releases/tag/0.8.0
Thanks for your work @mwarger.

Guys as you know this is an open source project that I work on in my free time(when I get any). So I really appreciate any help that comes to improve and maintain it.

Also, don't forget to star it and maybe even sponsor it if you find it useful at work :) 

Thank you