feat(shield): withShield optional string path
omar-dulaimi/prisma-trpc-generator pull request #78
Opened 2023-04-22 21:31 UTC by imsanchez

This is https://github.com/omar-dulaimi/prisma-trpc-generator/pull/65 but addressing @omar-dulaimi's of consistency with existing `string | boolean` pattern.

2023-04-23 17:46 UTC, omar-dulaimi commented
Hey @imsanchez


Thanks for the PR, I'll take a look very soon

2023-04-28 07:09 UTC, omar-dulaimi requested changes
Only thing remaining to do here is disabling shield generation when `withShield` is a string value.
Other than that, ready to merge!

2023-05-03 02:37 UTC, imsanchez commented
Ready for your approval @omar-dulaimi

2023-05-06 05:55 UTC, merged

2023-05-06 06:02 UTC, omar-dulaimi commented
Released in https://github.com/omar-dulaimi/prisma-trpc-generator/releases/tag/1.4.0

Thank you @imsanchez 
Keep them coming!